### ISSUE TITLE
alignment of numbers

### ISSUE THREAD

**Issue by skzap** [takamin/list-it#37]
I really like your module because it aligns numbers based on the decimals separator (.)

However I found this little bug happening with very small numbers

![https://i.imgur.com/fVcsvlQ.png](https://i.imgur.com/fVcsvlQ.png)

Please fix if you can :)

**Comment by takamin** [comment]
Hi, @skzap, Thanks to report this issue.

I published `list-it@1.3.6` on npm that fixed the bug.

If you could confirm the problems are gone, close this issue.
Best regards.

Courtesy of you, I could learn a lot of things about javascript's number type and exponential notation.
Thanks a lot.

**Comment by takamin** [comment]
The issue seems to have been fixed, so I would close.
